default:

  user_name: "tilt"
  password: "$7$C6..../....0gAprSr.fM1pwaLVuth49.43l5IGV2aKIjUii.7PPg2$FR.gxY35y3vuwicijK8h7HBUR1M8fw1SxDK4cy63L65"

toy:
  user_name: "toy"
  password: "$7$C6..../....oH/LsLbCKka4xHw762JvNQ1BtoR4qkhUPo9gMfhFXo7$l6VeVcyIMX5.vKOqkBfP/IPbK6tBqwNmUKSsFvZ0AL0"

