default:

  home:
    logo: "https://github.com/2DegreesInvesting/tiltWebTool/raw/main/inst/logo/logo.png"
    link: "https://www.tiltsmes.org/"

  download:
    text: "Request data"
    link: "https://docs.google.com/forms/d/e/1FAIpQLScWRHg5tKRKMi8TBR5YuahIhj2Lmn2i9V_wzBcdU_wJxO5RdQ/viewform"

  license:
    text: "CC BY-NC-ND 4.0"
    link: "https://creativecommons.org/licenses/by-nc-nd/4.0/"

  guide:
    text: "Download the climate action questionnaire"
    link: "https://github.com/user-attachments/files/16625497/Climate_Action_Questionnaire_tilt_user_platform.xlsx"

