default:

  home:
    # FIXME: Replace with a logo with transparent background
    logo: "https://github.com/2DegreesInvesting/tiltWebTool/blob/124_logo/inst/logo/logo.png?raw=true"
    link: "https://www.tiltsmes.org/"

  download:
    text: "Request data"
    link: "https://docs.google.com/forms/d/e/1FAIpQLScWRHg5tKRKMi8TBR5YuahIhj2Lmn2i9V_wzBcdU_wJxO5RdQ/viewform"

  license:
    text: "CC BY-NC-ND 4.0"
    link: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
