default:

  home:
    text: "tilt"
    link: "https://www.tiltsmes.org/"

  download:
    text: "Request data"
    link: "https://docs.google.com/forms/d/e/1FAIpQLScWRHg5tKRKMi8TBR5YuahIhj2Lmn2i9V_wzBcdU_wJxO5RdQ/viewform"
