default:

  welcome:
    header: "Welcome to *tilt*'s online portal"
    body: >
    Our mission is to empower Small and Medium Enterprises (SMEs) across the EU and 
    beyond with the funding and expertise needed to thrive in a net-zero future by 2050. 
   
    tilt  (Transforming in a Low Carbon Transition) is our data analytics solution 
    designed to provide financial institutions with critical climate data, enabling them 
    to offer SMEs the financing and knowledge essential for green transformation. 
    By bridging the SME data gap, tilt reduces costs for financial institutions 
    while supporting SMEs on their sustainability journey.
    
    Our goal is to drive investment in climate mitigation and adaptation by equipping 
    financial institutions with the insights needed to provide SMEs with targeted financing.
    
    Watch this video to learn more about tilt. 
    
    header: "What You’ll Find on This Website"
    body: >
    - **tilt’s Methodology** Explore our approach through training videos. 
    Our methodology links minimal data inputs from SMEs to climate data 
    (e.g., climate scenarios, Life-Cycle-Assessment data), generating climate indicators that 
    reveal a firm´s emission intensity and climate risks.
    - **Research Data** Access research data available for non-commercial use.  <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://www.tiltsmes.org/">the research data</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-ND 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1" alt=""></a></p>
    - **Climate Action Guide** Discover our climate action guide, which standardizes the collection 
    of revenue and climate action information from SMEs, improving data quality and enabling 
    tailored sustainability loans.
    
    These tools were developed under the CB-PASTAX program, funded by the EU. 
    We´ve tested our product with five EU banks, with input from 21 banks in total. 
    For applications beyond research, please visit www.tiltSMEs.org. 
    Our prototype is launching with full-coverage in the Netherlands soon.

    header: "We Value Your Feedback"
    body: >
    We strive for transparency and welcome input from financial institutions, researchers, and NGOs. 
    Join the tilt community and share your feedback here.  

  methodology:
    header: "Methodology"
    body: > 
    This paper introduces a methodology to derive climate metrics for SMEs,We present two indicators -
    a “relative emission indicator,” based on product emission intensity, and a “transition risk indicator,” 
    assessing risks from the low-carbon transition. These indicators, built using Life Cycle Assessment (LCA)
    and climate scenario data, are tested on a database of 250,000 firms across five European countries.
    Our method is reproducible, transparent, and scalable, requiring minimal data. It can be used to explore 
    SME low-carbon transformation, climate risks, or inform financial decision-making.
    Please find our methodology here.
    For further information and how to use the research data please watch these two online webinars.

