default:

  method:
    header: "Method"
    body: >
      [This
      paper](https://docs.google.com/document/d/1pmmNk-j8Bhr0iTZFiR0e_7DV_MglMlCL/edit#heading=h.z337ya)
      introduces the method behind *tilt* which is used to derive climate
      indicators for SMEs. We present two indicators: a relative emission
      indicator, based on product emission intensity, and a transition risk
      indicator, assessing risks from the low-carbon transition, based
      on sector-specific decarbonisation targets and emission intensity
      data. These indicators, built using Life Cycle Assessment (LCA) and
      climate scenario data, are applied to 250,000 firms across five European
      countries, creating the research data that can be requested at the tab
      Data. Our method is reproducible, transparent, and scalable, requiring
      only three data values: the product, the business type and the firm's
      location. It can be used to explore SMEs' climate profiles  or inform
      financial decision-making. For further information on how to use the
      research data, please watch the two online webinars below.

  dictionary:
    header: "Dictionary"
    body: >
      The data dictionary provides detailed descriptions of the *tilt* research
      data, including definitions, formats, and relationships for each data
      element. It serves as a guide to help you understand and utilize the data
      accurately and consistently within your analysis or applications.

  climate_action_guide:
    header: "Climate action guide"
    body: >
      A first version of our Climate Action Guide that collects revenue, and
      climate action information in a standardized way from the SME and can
      be used to (i) enhance the automated output data quality as well as (ii)
      engage with the SME clients and offer tailored sustainability improvement
      loans. SMEs only need 15 minutes to fill in the questionnaire with yes
      and no questions. We already tested the Climate Action Guide with 3 SMEs.
