default:

  welcome:
    header: "Welcome to *tilt*'s online portal"
    body: >
      *tilt* is a database designed to provide detailed insights into firms,
      primarily focusing on small and medium enterprises (SMEs). It offers
      extensive information on their climate profiles and transition risks
      associated with evolving environmental standards. Recognising that the
      creation of climate data involves a series of crucial decisions that
      significantly influence outcomes, *tilt* aims to empower its users to
      independently take these decisions. It allows them to thoughtfully consider
      these decisions and customise methodological choices to best suit their
      specific needs.

  methodology:
    header: "Methodology"
    body: >
      We are interested in making our methodology as transparent as possible and
      therefore welcome feedback from financial institutions, research community
      and NGO sphere. Please let us know if you would like to be part of the
      tilt community and offer your feedback.

      Contact us at https://www.tiltsmes.org/contact.

  dictionary:
    header: "Dictionary"
    body: >
      The data dictionary provides detailed descriptions of the *tilt* research
      data, including definitions, formats, and relationships for each data
      element. It serves as a guide to help you understand and utilize the data
      accurately and consistently within your analysis or applications.

  guide:
    header: "Climate action guide"
    body: >
      A first version of our climate action guide that collects revenue, and
      climate action information in a standardized way from the SME and can be
      used to (i) enhance the automated output data quality as well as (ii) engage
      with the SME clients and offer tailored sustainability improvement loans. The
      idea is that SMEs only need 15 minutes to fill in the questionnaire with
      "yes" and "no" questions. We already tested the Climate Action Guide with 3
      SMEs.
