default:

 welcome:
    header: "Welcome to *tilt*'s online portal"
    src: "https://youtu.be/5lTpwTqgj_0"
    width: 560
    height: 315
    
 method:
    header: "Methodology"
    src: "https://youtu.be/WXNCYmXq7nw"
    width: 560
    height: 315
