default:

  welcoming_page:
    paragraph_1: >
      ### Welcome to tilt's Online Portal

      Our mission is to empower Small and Medium Enterprises (SMEs) across
      the EU and beyond with the funding and expertise needed to thrive in
      a net-zero future by 2050.

    paragraph_2: >
      *tilt* (Transforming in a Low Carbon Transition) is our data analytics
      solution designed to provide financial institutions with critical
      climate data, enabling them to offer SMEs the financing and knowledge
      essential for green transformation.

    paragraph_3: >
      Our goal is to drive investment in climate mitigation and adaptation
      by equipping financial institutions with the insights needed to provide
      SMEs with targeted financing.

    paragraph_4: >
      This app covers all our work over the years under the
      [CB-PASTAX](https://webgate.ec.europa.eu/life/publicWebsite/project/LIFE20-GIC-DE-001765/climate-banking-paris-agreement-strategy-taxonomy-assessment)
      grant. For applications beyond research, please visit www.tiltSMEs.org.

    paragraph_5: >
      Watch this video to learn more about *tilt*.
